version: "2"
linters:
  default: all
  disable:
    - nlreturn # wsl_v5 is good enough.
    - wsl # deprecated.
    - exhaustruct # deprecated.
    - gomodguard # deprecated.
  settings:
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - generic
    depguard:
      rules:
        main:
          files:
            - $all
          allow:
            - $gostd
            - github.com/BurntSushi/toml
            - github.com/stretchr/testify
            - gopkg.in/yaml.v3
            - golift.io/cnfgfile
  exclusions:
    rules:
      - linters:
          - exhaustruct_v5
        path: (.+)_test\.go
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
