linters:
  enable-all: true
  disable:
    # deprecated
    - gomnd
    - execinquery

linters-settings:
  ireturn:
    allow: generic,stdlib,error
  depguard:
    rules:
      main:
        files:
        - $all
        allow:
        - $gostd
        - github.com/BurntSushi/toml
        - github.com/stretchr/testify
        - gopkg.in/yaml.v3

run:
  timeout: 2m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Exclude exhaustruct from testing files.
    - linters:
        - exhaustruct
      path: '(.+)_test\.go'
