linters:
  enable-all: true
  disable:
    # deprecated
    - tagalign
    - gomnd
    - execinquery
    # unused
    - exhaustruct
    - exhaustive
    - depguard
    - testifylint
run:
  timeout: 3m